### ISSUE TITLE
:latest is broken ?

### ISSUE THREAD

**Issue by kedare** [wallabag/docker#108]
Looks like the :latest image is broken ?

When trying to run it I get fatal errors at the first request 

```
Provisioner finished.                                                                                                                  [82/664]
2018/03/24 14:43:37 [error] 209#209: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Symfony\Component\Asset\Exception\InvalidArgumentException: "wallabag.eolo.kedare.net" is not a valid URL in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Asset/Url
Package.php:133
Stack trace:                                                                                                                                   #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Asset/UrlPackage.php(62): Symfony\Component\Asset\UrlPackage->getSslUrls(Arra
y)
#1 /var/www/wallabag/var/cache/prod/appProdProjectContainer.php(760): Symfony\Component\Asset\UrlPackage->__construct(Array, Object(Symfony\Component\Asset\VersionStrategy\EmptyVersionStrategy), Object(Symfony\Component\Asset\Context\RequestStackContext))
#2 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Container.php(329): appProdProjectContainer->getAssets_Pa
ckagesService()                                                                                                                                #3 /var/www/wallabag/var/cache/prod/appProdProjectContainer.php(5747): Symfony\Component\DependencyInjection\Container->get('assets.packages')
#4 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/" while reading response header from upstream, client: 172.18.0.3, server: _,
 request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.xxxx"
```

Deployed through Ansible: 
```
- name: Setup Wallabag Container                                                                                                  [34/2010]
      docker_container:
        name: wallabag
        image: wallabag/wallabag:latest
        state: started
        env:
          SYMFONY__ENV__DOMAIN_NAME: "https://wallabag.xxxx/"
          POPULATE_DATABASE: true
        networks:
          - name: network0
        volumes:
          - "/var/lib/wallabag:/var/www/wallabag/data"
          - "/var/log/wallabag:/var/www/wallabag/var/logs"
        labels:
          traefik.backend: "wallabag"
          traefik.docker.network: "network0"
          traefik.frontend.rule: "Host:wallabag.xxxx"
          traefik.enable: "true"
          traefik.port: "80"
          traefik.default.protocol: "http"
```

When falling back to :3.2.3, everything works fine
