### ISSUE TITLE
SYMFONY__ENV__DOMAIN_NAME set, but confirmation mail from localhost

### ISSUE THREAD

**Issue by itsthejb** [wallabag/docker#122]
Hi,

Just getting Wallabag running for the first time, but having issues getting my domain to come through on the confirmation email:

```
Hello itsthejb! 

To finish activating your account - please visit http://0.0.0.0:5841/register/confirm/FlEgET0IMMZT6BxCGfJuMjEW4RG91wNmL02YB4rFbt4 

This link can only be used once to validate your account. 

Regards, 
the Team. 
```

My `docker-compose.yml`:

```
  wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    environment:
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.myhost.org
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__MAILER_HOST=192.168.178.22
      - SYMFONY__ENV__MAILER_USER=email@myemail.com
      - SYMFONY__ENV__MAILER_PASSWORD=emailpassword
      - SYMFONY__ENV__FROM_EMAIL=wallabag@myhost.org
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
    ports:
      - "5841:80"
    volumes:
      - /docker/appdata/wallabag/images:/var/www/wallabag/web/assets/images
```

It seems from other issues that only `SYMFONY__ENV__DOMAIN_NAME` is required, but no luck. What am I getting wrong?

Thanks
