### ISSUE TITLE
Startup fails with `unable to find /root/.my.cnf`

### ISSUE THREAD

**Issue by m-strasser** [wallabag/docker#153]
I'm trying to set up the wallabag docker container on a Raspberry Pi 3 running Raspbian.

I cloned the repository, built the image from the `Dockerfile` and exchanged the images in the `docker-compose.yml` accordingly (`wallabag_rpi` and `rpi-mariadb`):

```
version: '3'
services:
  wallabag:
    image: wallabag_rpi
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql                                   
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag                                      
      - SYMFONY__ENV__DATABASE_USER=wallabag                                      
      - SYMFONY__ENV__DATABASE_PASSWORD=mydbpassword          
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4                                    
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1                                       
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@mydomain.com                          
      - SYMFONY__ENV__DOMAIN_NAME=wallabag.mydomain.com                        
    ports:
      - "8002:80"
    volumes:
      - wallabag:/var/www/wallabag/data
      - wallabag_images:/var/www/wallabag/web/assets/images                       
  db:
    image: monstrenyatko/rpi-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot                      
    volumes:
      - /opt/wallabag/data:/var/lib/mysql                                         
volumes:
  wallabag:
  wallabag_images:
```

Starting a `wallabag_rpi` container then failes with:
```
Starting provisioner...
 [WARNING]: Found both group and host with same name: localhost
PLAY [localhost] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var 
TASK [Gathering Facts] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] 
TASK [needed dirs] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] => (item=/var/www/wallabag/app) ok: [localhost] => (item=/var/www/wallabag/app/config) ok: [localhost] => (item=/var/www/wallabag/data) ok: [localhost] => (item=/var/www/wallabag/data/assets) ok: [localhost] => (item=/var/www/wallabag/data/db) 
TASK [write parameters.yml] bin dev entrypoint.sh etc home lib media
mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] 
TASK [stat] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] 
TASK [notify install for sqlite] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] 
TASK [wait for db container] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] 
TASK [add mariadb db] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var fatal: [localhost]: 
FAILED! => {"changed": false, "msg": "unable to find /root/.my.cnf. Exception message: (1045, \"Access denied for user 'root'@'172.19.0.2' (using password: YES)\")"} to retry, use: --limit @/etc/ansible/entrypoint.retry 
PLAY RECAP bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var localhost : ok=4 changed=0 unreachable=0 failed=1  
Provisioner finished.
```
