### ISSUE TITLE
Unable to access container: 500 error in browser.

### ISSUE THREAD

**Issue by LilTrublMakr** [wallabag/docker#172]
I am trying to get an instance of Wallabag working behind Traefik reverse proxy. I believe I have my compose file set up correctly but when I try to access the link, I get a 500 error in the browser.

Docker-compose:
```
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag-app
    restart: unless-stopped
    networks:
      - proxy
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=totallynotthepassword
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=completelydiffpass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DOMAIN_NAME=https://my.url.com
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - 6901:80
    volumes:
      - ${DOCKERDIR}/wallabag/images:/var/www/wallabag/web/assets/images
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=links'
      - 'traefik.docker.network=proxy'
      - 'traefik.frontend.rule=Host:links.${DOMAIN}'
      - 'traefik.port=80'
      - 'traefik.frontend.entryPoints=https'
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - db
    environment:
      - MYSQL_ROOT_PASSWORD=totallynotthepassword
    volumes:
      - ${DOCKERDIR}/wallabag/data:/var/lib/mysql
  redis:
    image: redis:alpine
    container_name: redis
    restart: always

networks:
  db:
    external: false
  proxy:
    external: true
```

Error from terminal when trying to access the site:
```
Starting provisioner...,
 [WARNING]: Found both group and host with same name: localhost,
Provisioner finished.,
2019/11/13 17:18:44 [error] 249#249: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2636PHP message: PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/wallabag/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php on line 2665PHP message: PHP Fatal error:  Uncaught RuntimeException: Setting "piwik_enabled" couldn't be found. in /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php:182,
Stack trace:,
#0 /var/www/wallabag/vendor/craue/config-bundle/Util/Config.php(77): Craue\ConfigBundle\Util\Config->createNotFoundException('piwik_enabled'),
#1 /var/www/wallabag/vendor/craue/config-bundle/Twig/Extension/ConfigTemplateExtension.php(96): Craue\ConfigBundle\Util\Config->get('piwik_enabled'),
#2 /var/www/wallabag/var/cache/prod/twig/e5/e59b3c6ba046bc5541ec427c6fe013ac603e567122ed934d6dc17178083d1b89.php(96): Craue\ConfigBundle\Twig\Extension\ConfigTemplateExtension->getSetting('piwik_enabled'),
#3 /var/www/wallabag/vendor/twig/twig/src/Template.php(443): __TwigTemplate_248ffdebaf41f0c401270de5135adaa2a06bcf1a73c1cf5c0f36284706bf3bb5->doDisplay(Array, Array),
#4 /var/www/wallabag/vendor/twig/twig/src/Template.php(414): Twig\Template->displayWithErrorHandling(Array, Array),
#5 /var/www/wallabag/var/cache/prod/twig/d9/d956e063b" while reading response header from upstream, client: 172.18.0.3, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "my.url.com",
172.18.0.3 - - [13/Nov/2019:17:18:44 -0500] "GET /login HTTP/1.1" 500 31 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
```

Any help would be appreciated.
