### ISSUE TITLE
All interface enrichments are erased

### ISSUE THREAD

**Issue by asitemade4u** [wallabag/docker#184]
- I have installed the SQLite docker version of Wallabag.
- I attach the `docker-compose.yml` file I am using (I convert it to a TXT file + and I obfuscate the server name)
[docker-compose.txt](https://github.com/wallabag/docker/files/4363300/docker-compose.txt)

.
- I can connect using the `wallabag/wallabag` login and password.
- But all decorations in the interface are erased: no images, no page setup...

![Screenshot-20200321-122638](https://user-images.githubusercontent.com/11460106/77231187-bd518680-6b6f-11ea-9e98-4d2c4c581442.png)

Concurrently, the container log issues an error:

![Screenshot-20200321-123123](https://user-images.githubusercontent.com/11460106/77231207-e3772680-6b6f-11ea-9636-a58b448c5b1c.png)

Please help because the current version of the application is really barren...

**Comment by flyingnobita** [comment]
@asitemade4u I had the same problem.  Setting the correct SYMFONY__ENV__DOMAIN_NAME solves it for me

**Comment by asitemade4u** [comment]
Which I had done. But still does not work.

**Comment by sductor** [comment]
with https://…
 (http does not work - i'm using lets encrypt)

**Comment by victorbrca** [comment]
I'm going to add to this existing issue because it seems that I have the same problem, and I think I found what's causing it. 

In my case, it looks like when exposing a port other than what's used by Nginx, the port is not getting translated all across. So while some requests go to the exposed host port (my case 5841), others (like loading javascript) go to the internal container port (80). 

![2021-02-20_19-01](https://user-images.githubusercontent.com/9310736/108611757-b2baf500-73af-11eb-8f30-cac7b27d418d.png)

Changing the exposed port to '80' fixes it for me (going to try changing the default Nginx port). 

Here's my working docker-compose.yml:

```yml
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=victorbrca@gmail.com
      - SYMFONY__ENV__DOMAIN_NAME=http://wallabag.localdomain.com
      - SYMFONY__ENV__SERVER_NAME="Docker wallabag instance"
    ports:
      # - 5841:80
      - 80:80
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - ./data:/var/lib/mysql
  redis:
    image: redis:alpine
```
