### ISSUE TITLE
Instagram, and Pocket import not working with redis.

### ISSUE THREAD

**Issue by im-sky** [wallabag/docker#209]
I haven't been able to successfully run import from Pocket or Instapaper with redis. 
A few remarks-

1. I am using mariadb for database.
2. Without redis, import works. However, the process times out after importing only a few hundred articles out of a total of a thousand plus articles. Running the same import again results in duplicate articles, rather than the next few hundred articles.
3. Here's my docker-compose.yaml
```
version: '3'                                                          
services:                                                             
    wallabag:                                                         
        container_name: wallabag                                      
        image: wallabag/wallabag                                      
        restart: always                                               
        depends_on:                                                   
            - db                                                      
            - redis                                                   
        environment:                                                  
            - MYSQL_ROOT_PASSWORD=wallaroot
            - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql                 
            - SYMFONY__ENV__DATABASE_HOST=db                          
            - SYMFONY__ENV__DATABASE_PORT=3306                        
            - SYMFONY__ENV__DATABASE_NAME=wallabag                    
            - SYMFONY__ENV__DATABASE_USER=wallabag                    
            - SYMFONY__ENV__DATABASE_PASSWORD=wallapass               
            - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4                  
            - SYMFONY__ENV__FOSUSER_REGISTRATION=false                
            - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.com
        ports:                                                        
            - "41238:80"                                              
        volumes:                                                      
            - /opt/wallabag/images:/var/www/wallabag/web/assets/images
                                                                      
    db:                                                               
        image: mariadb                
        restart: always                                               
        environment:                                                  
            - MYSQL_ROOT_PASSWORD=wallaroot
        volumes:                                                      
            - /opt/wallabag/data:/var/lib/mysql                       
                                                                      
    redis:                                                            
        image: redis:alpine                                           
```
4. Wallabag acknowledges that it can find Redis because on the import page it says on the top `Import is made asynchronously. Once the import task is started, an external worker will handle jobs one at a time. The current service is: Redis`.

I will be more than happy to provide any logs or any other information needed to debug this issue. Please note I am new to Wallabag and dockers in general.
