### ISSUE TITLE
Web UI has no styling?

### ISSUE THREAD

**Issue by linareyne** [wallabag/docker#214]
<img width="821" alt="Screen Shot 2020-09-28 at 01 58 21" src="https://user-images.githubusercontent.com/20880695/94395653-2244f500-012e-11eb-9967-bf8391fc683a.png">

On an NUC with the following...

```
wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    environment:
      - SYMFONY__ENV__TWOFACTOR_AUTH=false
      - SYMFONY__ENV__FOSUSER_CONFIRMATION=false
    volumes:
      - /media/mhmm/configs/wallabag:/var/www/wallabag/web/assets/images
    ports:
      - 7777:80
    restart: always
```
