### ISSUE TITLE
container stopped: exit 0

### ISSUE THREAD

**Issue by meonkeys** [wallabag/docker#217]
I've been running a wallabag container on a GNU/Linux Docker host for a few days. A few times so far (maybe once per day?) I've noticed the Android app reporting an error, and I find the container has exited with a successful return code of zero. I haven't found a pattern or root cause. The last line in the docker-compose log is

```
wallabag_app_1 exited with code 0
```

Before that I see a mix of https://github.com/wallabag/docker/issues/185 and normal-looking HTTP requests. In other words, no obvious root causes. Is there another log I should be checking? Any other debugging tips?

Here's my `docker-compose.yml` file:

```yaml
version: '3.5'

services:
  app:
    image: wallabag/wallabag
    environment:
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: db
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: REDACTED
      SYMFONY__ENV__DATABASE_PASSWORD: 'REDACTED'
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__REDIS_HOST: redis
      SYMFONY__ENV__REDIS_PASSWORD: REDACTED
      SYMFONY__ENV__MAILER_HOST: mail
      SYMFONY__ENV__MAILER_USER: ~
      SYMFONY__ENV__MAILER_PASSWORD: ~
      SYMFONY__ENV__FROM_EMAIL: REDACTED
      SYMFONY__ENV__TWOFACTOR_AUTH: 'true'
      SYMFONY__ENV__FOSUSER_REGISTRATION: 'false'
      SYMFONY__ENV__FOSUSER_CONFIRMATION: 'true'
      SYMFONY__ENV__DOMAIN_NAME: http://wallabag.localdomain
      POPULATE_DATABASE: 'no'
    volumes:
      - /opt/wallabag/data:/var/www/wallabag/data
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_default"
      - "traefik.http.routers.wallabag.entrypoints=web"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag`, `wallabag.localdomain`)"
      # local only
      - "traefik.http.middlewares.wallabag-allow.ipwhitelist.sourcerange=192.168.1.0/24"
      - "traefik.http.routers.wallabag.middlewares=wallabag-allow@docker"
    networks:
      - wallabag
      - traefik_default
      - mariadb
      - mail_default
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --requirepass REDACTED
    networks:
      - wallabag
networks:
  wallabag:
    name: wallabag
  traefik_default:
    external: true
  mariadb:
    external: true
  mail_default:
    external: true
```
