### ISSUE TITLE
404 not found + weird domain behaviour when starring/deleting

### ISSUE THREAD

**Issue by jt196** [wallabag/docker#219]
Hi there - so when I star or delete something (haven't been through all the behaviours yet), I get a weird domain behaviour. The page redirects to (for example): `https://<my_wallabag_domain>/star/192.168.1.77`, where the IP address is the address of my host NAS. This is a subdomain installation running behind a Nginx reverse proxy, so I'm guessing it's something to do with my Nginx config. 

My Docker-compose file:

```
version: '3.3'
services:
    wallabag:
        container_name: wallabag
        restart: always
        ports:
            - '8084:80'
        image: wallabag/wallabag
        volumes:
            - /volume1/docker/wallabag/images:/var/www/wallabag/web/assets/images
            - /volume1/docker/wallabag/data/:/var/www/wallabag/data/
        environment: 
            - SYMFONY__ENV__DOMAIN_NAME=https://<my_domain>
            - SYMFONY__ENV__FOSUSER_REGISTRATION=false
```
And my Nginx config:

```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name <my_domain>;

    ssl_certificate /usr/syno/etc/certificate/ReverseProxy/<cert>/fullchain.pem;

    ssl_certificate_key /usr/syno/etc/certificate/ReverseProxy/<cert>/privkey.pem;

    add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload" always;

    location / {

        proxy_connect_timeout 60;

        proxy_read_timeout 60;

        proxy_send_timeout 60;

        proxy_intercept_errors off;

        proxy_http_version 1.1;

        proxy_set_header        X-Forwarded-Host            $http_host;

        proxy_set_header        X-Forwarded-Proto            $scheme;

        proxy_set_header        X-Forwarded-For            $proxy_add_x_forwarded_for;

        proxy_set_header        X-Forwarded-Protocol            $scheme;

        proxy_set_header        X-Forwarded-Server            $host;

        proxy_set_header        Host            $host;

        proxy_set_header        Referer            $server_addr;

        proxy_set_header        Origin            $server_addr;

        proxy_set_header        X-Real-IP            $remote_addr;

        proxy_pass http://localhost:8084;

        proxy_redirect "http://<my_domain>/" "https://<my_domain>/";

    }

    error_page 403 404 500 502 503 504 @error_page;

    location @error_page {
        root /usr/syno/share/nginx;
        rewrite (.*) /error.html break;
        allow all;
    }

}
```
I'm not quite sure where the local IP address of the NAS comes up as it's not in any of the config or the above files. Could it be persistent from a previous installation? 

There's also a proxy redirect in there I had to get it working, maybe that's something to do with it. 

Thanks for the help in advance!

J
