### ISSUE TITLE
Fresh deployment fails to start

### ISSUE THREAD

**Issue by pcwilcox** [wallabag/docker#224]
Docker log:

```
 ❯ docker logs -f wallabag
Starting provisioner...
[WARNING]: Found both group and host with same name: localhost
[WARNING]: Platform linux on host localhost is using the discovered Python
interpreter at /usr/bin/python3, but future installation of another Python
interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen
ce_appendices/interpreter_discovery.html for more information.
PLAY [localhost] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var TASK [Gathering Facts] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [needed dirs] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] => (item=/var/www/wallabag/app) ok: [localhost] => (item=/var/www/wallabag/app/config) ok: [localhost] => (item=/var/www/wallabag/data) ok: [localhost] => (item=/var/www/wallabag/data/assets) ok: [localhost] => (item=/var/www/wallabag/data/db) TASK [write parameters.yml] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [stat] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [notify install for sqlite] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [wait for db container] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [add mariadb db] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [add mariadb user] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [postgresql db] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [add postgresql user] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var skipping: [localhost] TASK [remove cache] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var ok: [localhost] TASK [run composer] bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var fatal: [localhost]: FAILED! => {"changed": true, "cmd": "SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist", "delta": "0:00:00.076155", "end": "2020-12-08 00:36:53.618402", "msg": "non-zero return code", "rc": 1, "start": "2020-12-08 00:36:53.542247", "stderr": "Composer could not find a composer.json file in /var/www/wallabag\nTo initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section", "stderr_lines": ["Composer could not find a composer.json file in /var/www/wallabag", "To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section"], "stdout": "", "stdout_lines": []} PLAY RECAP bin dev entrypoint.sh etc home lib media mnt opt proc root run sbin srv sys tmp usr var localhost : ok=5 changed=0 unreachable=0 failed=1 skipped=6 rescued=0 ignored=0
Provisioner finished.
```

docker-compose.yml:

```
  wallabag:
    image: wallabag/wallabag
    container_name: wallabag
    restart: unless-stopped
    environment:
      - PUID=501
      - PGID=1000
      - TZ=America/Los_Angeles
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db.local
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=db_password
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=smtp.gmail.com:587
      - SYMFONY__ENV__MAILER_USER=email@gmail.com
      - SYMFONY__ENV__MAILER_PASSWORD=secret
      - SYMFONY__ENV__FROM_EMAIL=wallabag@domain.tld
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.domain.tld
      - POPULATE_DATABASE=no
    ports:
      - 8200:80
    volumes:
      - /path/to/wallabag:/var/www/wallabag
```

Seems like a composer file is not being deployed correctly?
