### ISSUE TITLE
I still can't get Wallabag to work!

### ISSUE THREAD

**Issue by aashish108** [wallabag/docker#235]
Hi all, I waited for the 2.4.0 release for quite a long time as I hoped things would be better in terms of setting up. Unfortunately, it's issue after issue. I'm hoping someone can help pls?

On a clean setup, after the docker compose is running and Wallabags provisioner is finished, I run `sudo docker exec -t 24af76b0bca7 /var/www/wallabag/bin/console wallabag:install --env=prod --no-interaction` to install (not documented anywhere but I believe this step is to be done otherwise other errors occur).

The errors I get are:

```

wallabag installer
==================

Step 1 of 4: Checking system requirements.
------------------------------------------

 ------------------------- -------- ----------------
  Checked                   Status   Recommendation
 ------------------------- -------- ----------------
  PDO Driver (pdo_sqlite)   OK!
  Database connection       OK!
  Database version          OK!
  curl_exec                 OK!
  curl_multi_init           OK!
 ------------------------- -------- ----------------


 [OK] Success! Your system can run wallabag properly.


Step 2 of 4: Setting up database.
---------------------------------

 Creating schema...
 Clearing the cache...

In InstallCommand.php line 337:

  The command "cache:clear" generates some errors:


   // Clearing the cache for the prod environment with debug false


  In AbstractMySQLDriver.php line 97:

    An exception occurred in driver: SQLSTATE[HY000] [2002] Operation timed out


  In PDOConnection.php line 31:

    SQLSTATE[HY000] [2002] Operation timed out


  In PDOConnection.php line 27:

    SQLSTATE[HY000] [2002] Operation timed out


  cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

```

But, if I ignore it, I go to my Wallabag instance and I see JS/CSS trying to be loaded from `your-wallabag-url-instance.com`. Not sure how that's possible considering the below compose file adds my URL in? 

Note that the https gets terminated at my reverse proxy and from there its all http to the docker.

This is my docker-compose file:
```
version: '3'
services:

  wallabag:
    image: wallabag/wallabag:2.4.0
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=${WALLABAG_DB_NAME}
      - SYMFONY__ENV__DATABASE_USER=${WALLABAG_DB_USER}
      - SYMFONY__ENV__DATABASE_PASSWORD=${WALLABAG_DB_PASSWORD}
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      # - SYMFONY__ENV__DATABASE_DRIVER_CLASS=Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
      - SYMFONY__ENV__MAILER_HOST=${WALLABAG_MAILER_HOST}
      - SYMFONY__ENV__MAILER_USER=${WALLABAG_MAILER_USER} 
      - SYMFONY__ENV__MAILER_PASSWORD=${WALLABAG_MAILER_PASSWORD}
      - SYMFONY__ENV__FROM_EMAIL=${WALLABAG_MAILER_FROM_EMAIL}
      - SYMFONY__ENV__DOMAIN_NAME=${WALLABAG_DOMAIN_NAME}
      - SYMFONY__ENV__REDIS_HOST=wallabag-redis
    ports:
      - "${WALLABAG_PORT}:80"
    volumes:
      - ${WALLABAG_IMAGES_FOLDER}:/var/www/wallabag/web/assets/images
      # - ${WALLABAG_DATA_FOLDER}:/var/www/wallabag/data
    depends_on:
      - wallabag-db
      - wallabag-redis
    restart: unless-stopped
    networks:
      - wallabag-net

  wallabag-db:
    image: mariadb
    environment:
      - MYSQL_USER=${WALLABAG_DB_USER}
      - MYSQL_PASSWORD=${WALLABAG_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=wallaroot
      - MYSQL_DATABASE=${WALLABAG_DB_NAME}
      - PUID=1000
      - PGID=1000
    volumes:
      - ${WALLABAG_DB_DATA_FOLDER}:/var/lib/mysql
    restart: unless-stopped
    networks:
      - wallabag-net

  wallabag-redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - wallabag-net

networks:  
  wallabag-net:

```

This is my .env file:

```
 WALLABAG_IMAGES_FOLDER=/volume1/Cloud/wallabag/images
WALLABAG_DATA_FOLDER=/volume1/Cloud/wallabag/data
WALLABAG_DB_NAME=wallabag
WALLABAG_DB_USER=wallbag
WALLABAG_DB_PASSWORD=wallabag
WALLABAG_MAILER_HOST=mail.redacted.space
WALLABAG_MAILER_USER=me@redacted.space
WALLABAG_MAILER_PASSWORD=50v3r319n1089801*
WALLABAG_MAILER_FROM_EMAIL=me@redacted.space
WALLABAG_DOMAIN_NAME=https://wallabag.redacted.space
WALLABAG_PORT=8385
WALLABAG_DB_DATA_FOLDER=/volume1/Cloud/wallabag/db
```

Thanks
