### ISSUE TITLE
Can't update from 2.4.0 to 2.4.2

### ISSUE THREAD

**Issue by rafaelmr2** [wallabag/docker#255]
Hi,

When I try to update from 2.4.0 to 2.4.2 (build with the Dockerfile to use sqlite) , I got the error:

```
Some parameters are missing. Please provide them.
server_name ('Your wallabag instance'): Script Incenteev\ParameterHandler\ScriptHandler::buildParameters handling the post-cmd event terminated with an exception

[Symfony\Component\Console\Exception\RuntimeException]
Aborted

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...

ERROR: Service 'wallabag' failed to build : The command '/bin/sh -c set -ex  && cd /var/www/wallabag  && SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist --no-progress  && chown-R nobody:nobody /var/www/wallabag' returned a non-zero code: 1
```

Here is may `docker-compose.yml`:

```
version: '3'
services:
  wallabag:
    build:
    context: ./
    image: wallabag:sqlite
    container_name: wallabag
    restart: unless-stopped
    environment:
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_sqlite
      - SYMFONY__ENV__DOMAIN_NAME=https://***
      - SYMFONY__ENV__SERVER_NAME="***"
    ports:
      - 8000:80
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
      - /opt/wallabag/data:/var/www/wallabag/data
```

Thanks!!
