### ISSUE TITLE
Wallabag container never actually successfully starts up again after the initial run and installation.

### ISSUE THREAD

**Issue by GlassedSilver** [wallabag/docker#286]
Basically it never survived the reboot.

I got one run and that was one hell to setup.

I'm using docker compose with Postgres and redis.

My Wallabag container basically just cycles through this over and over again:

```
Starting provisioner...

[WARNING]: Found both group and host with same name: localhost

[WARNING]: Platform linux on host localhost is using the discovered Python

interpreter at /usr/bin/python3, but future installation of another Python

interpreter could change this. See https://docs.ansible.com/ansible/2.9/referen

ce_appendices/interpreter_discovery.html for more information.
```

This is my docker-compose.yml:

```
# Wallabag is a self hostable application for saving web pages. Unlike other services, wallabag is free (as in freedom) and open source.
#
# Default user/password
# User: wallabag
# Password: wallabag

version: "3.4"
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<REDACTED>
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_pgsql
      - SYMFONY__ENV__DATABASE_HOST=wallabag-db
      - SYMFONY__ENV__DATABASE_PORT=5432
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      # We don't need the database password, since Postgres is set up to trust
      # - SYMFONY__ENV__DATABASE_PASSWORD=<REDACTED>
      - SYMFONY__ENV__DATABASE_CHARSET=utf8
      - SYMFONY__ENV__DOMAIN_NAME=<REDACTED>
      - SYMFONY__ENV__SERVER_NAME=<REDACTED>
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - POPULATE_DATABASE=False
    ports:
      - "55771:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"   # Use Host time
      - "wallabag-images:/var/www/wallabag/web/assets/images"
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - redis
      - wallabag-db
    links:
      - "wallabag-db:wallabag-db" # resolve the hostname "wallabag-db" with the ip of the wallabag-db container

  wallabag-db:
    image: postgres:11-alpine
    restart: unless-stopped
    hostname: wallabag-db
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=wallabag
      - POSTGRES_PASSWORD=<REDACTED>
      - POSTGRES_DB=wallabag
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "/etc/localtime:/etc/localtime:ro"   # Use Host time
      - "wallabag-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  redis:
    image: redis:alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "<REDACTED>"
  wallabag-images:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "<REDACTED>"

```

I am absolutely at the end of my wisdom, I have never had a deployment this hard to get done and most importantly:

It did run, but after a restart of the container: NADA.

What the hell?
