### ISSUE TITLE
Can Not Create a New API

### ISSUE THREAD

**Issue by huangwb8** [wallabag/docker#293]
Here is my docker-compose.yml file for wallabag installation in Docker:

```yaml
version: '3'
services:
  app:
    image: wallabag/wallabag:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=password2
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=example@qq.com   # 修改成你自己的邮箱
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.example.com  # 修改成稍后要反向代理的域名
      - SYMFONY__ENV__SERVER_NAME="example"
    ports:
      - 1234:80
    volumes:
      - ./images:/var/www/wallabag/web/assets/images
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
      
  db:
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=wallabag
      - MYSQL_USER=wallabag
      - MYSQL_PASSWORD=password2
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 20s
      timeout: 3s
      
  redis:
    image: redis:alpine
    restart: unless-stopped
    networks:
      - default
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
   
networks:
  default:
    name: wallabag

```

However, when I want to create an API client, something weird happened:

![chrome_5IB5rc2gjc](https://user-images.githubusercontent.com/35643122/173228482-4807e8d4-a7c8-4d98-953f-e0671f8829ba.gif)

The creation of an API client could never succeed. 

Any suggestions?
