### ISSUE TITLE
gif images are not animated

### ISSUE THREAD

**Issue by a1ekseev** [wallabag/docker#323]
### Environment

* **Version**:  2.5.4
* **Installation**: Docker
* **PHP version**: In Docker Container - 8.1.15
* **OS**: Ubuntu 22.04
* **Database**:PostgreSQL
* **Parameters**:

```yml
parameters:
    database_driver: pdo_pgsql
    database_host: postgres
    database_port: 5432
    database_name: wallabag
    database_user: wallabag
    database_password: password
    database_path: '%kernel.root_dir%/../data/db/wallabag.sqlite'
    database_table_prefix: wallabag_
    database_socket: null
    database_charset: utf8
    domain_name: 'https://wallabag.host.dev'
    server_name: Wallabag
    mailer_transport: smtp
    mailer_user: null
    mailer_password: null
    mailer_host: 127.0.0.1
    mailer_port: 25
    mailer_encryption: null
    mailer_auth_mode: null
    locale: en
    secret: secret
    twofactor_auth: false
    twofactor_sender: no-reply@wallabag.org
    fosuser_registration: true
    fosuser_confirmation: false
    fos_oauth_server_access_token_lifetime: 3600
    fos_oauth_server_refresh_token_lifetime: 1209600
    from_email: wallabag@host.dev
    rss_limit: 50
    rabbitmq_host: localhost
    rabbitmq_port: 5672
    rabbitmq_user: guest
    rabbitmq_password: guest
    rabbitmq_prefetch_count: 10
    redis_scheme: tcp
    redis_host: redis
    redis_port: 6379
    redis_path: null
    redis_password: null
    sentry_dsn: null
```

### What steps will reproduce the bug?

Import this link - https://habr.com/ru/post/711968/

After importing the link gif images are not animated.
