### ISSUE TITLE
Wallabag Docker Redis Import Not Working

### ISSUE THREAD

**Issue by pihat74622** [wallabag/docker#369]
Using the official docker compose (and some editing on the db healthcheck and used an .env file).

I added some service in the docker compose for the import worker:

```
   #import-worker
  import-firefox:
    container_name: import-firefox
    image: wallabag/wallabag
    env_file: ./wallabag.env
    depends_on:
      - db
      - redis
    command: |
      import firefox
``` 

This service must be identical with the official docker run command for the import worker.

However, importing some firefox json bookmarks container 3 bookmarks just for testing, seems to be not working. Just nothing happens. No logs happening on the redis service.

The beginning of the logs of the import worker after uploading the json file:

```
>  [OK] All assets were successfully installed.                                   
Worker started at: 24-08-2023 12:58:45
Waiting for message ...
13:00:54 WARNING   [app] Entry is invalid ["entry" => ["bookmark_bar" => ["children" => 
and all the bookmark contents in json
``` 

However, after that, nothing is happening. No activities on the redis logs.

What could be the problem?
