### ISSUE TITLE
Wallabag mariadb:  Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.29.0.33' (This connection closed normally without authentication)

### ISSUE THREAD

**Issue by jeff47** [wallabag/docker#380]
I am seeing the following error/warning in my the logs of the wallabag-db docker container.  I saw this error coming up and decided to reinstall everything, since I had only a few things saved.  I removed the whole wallabag volume and reinstalled, but the warning is still there.

Any clues on how to troubleshoot?

```
wallabag-db  | 2023-09-14 18:38:20 0 [Note] Starting MariaDB 11.1.2-MariaDB-1:11.1.2+maria~ubu2204 source revision 9bc25d98209df6810f7a7d5e7dd3ae677a313ab5 as process 1
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Number of transaction pools: 1
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
wallabag-db  | 2023-09-14 18:38:20 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Using liburing
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Completed initialization of buffer pool
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: End of log at LSN=47375
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Opened 3 undo tablespaces
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: log sequence number 47375; transaction id 14
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
wallabag-db  | 2023-09-14 18:38:20 0 [Note] Plugin 'FEEDBACK' is disabled.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] Plugin 'wsrep-provider' is disabled.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] InnoDB: Buffer pool(s) load completed at 230914 18:38:20
wallabag-db  | 2023-09-14 18:38:20 0 [Note] Server socket created on IP: '0.0.0.0'.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] Server socket created on IP: '::'.
wallabag-db  | 2023-09-14 18:38:20 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
wallabag-db  | 2023-09-14 18:38:20 0 [Note] mariadbd: ready for connections.
wallabag-db  | Version: '11.1.2-MariaDB-1:11.1.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
wallabag-db  | 2023-09-14 18:38:20 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '172.29.0.33' (This connection closed normally without authentication)
```

**Comment by benjamin051000** [comment]
I see the same thing, and the container is listed as unhealthy.

**Comment by jeff47** [comment]
> I see the same thing, and the container is listed as unhealthy.

I _think_ this might be related to https://github.com/wallabag/docker/issues/381.  When I fixed the healthcheck, the connected error went away. 

Try changing your docker-compose.yml to look like this:

```
  wallabag-db:
    image: mariadb
    container_name: wallabag-db
    restart: unless-stopped
    env_file: docker.env
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - ./wallabag/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh" ,"--innodb_initialized"]
      start_period: 5s
      interval: 20s
      timeout: 3s
      retries: 5
```

**Comment by cboergermann** [comment]
> Doesn't work for me, I get `[Warning] Access denied for user 'root'@'localhost' (using password: NO)`. 🤔 When I instead use `test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect" ]`, my container is no longer unhealthy, but in its logs I still see `[Warning] Access denied for user 'mysql'@'127.0.0.1' (using password: NO)` which is basically the same as before where the connecting user was `root`.
> 
> Also, the main wallabag container apparently can't connect to the database anymore, even though I'm able to open a shell in there and run `mysql -h db ${SYMFONY__ENV__DATABASE_NAME} -u${SYMFONY__ENV__DATABASE_USER} -p${SYMFONY__ENV__DATABASE_PASSWORD}`. When trying to log in through the web interface though, I only see `Authentication request could not be processed due to a system problem.` which would be somewhat of a coincidence if it was totally unrelated to the issue described before (even though I have not enabled more extensive logging to verify that). Any ideas?

Same here :(

**Comment by AloisCRR** [comment]
I had the same problem and managed to solve it by using docker volumes instead of bind mounts. Here's my docker-compose. Remember to set the `SYMFONY__ENV__DOMAIN_NAME` env variable to the host of your server, in my case I'm hosting it in my RPi so it's in lan.

```yaml
version: '3'
services:
  wallabag:
    image: wallabag/wallabag
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
      - SYMFONY__ENV__DOMAIN_NAME=http://192.168.1.10:8082
      - SYMFONY__ENV__SERVER_NAME="Your wallabag instance"
    ports:
      - 8082:80
    volumes:
      - wallabag-images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - db
      - redis
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - wallabag-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']

      interval: 20s
      timeout: 3s
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s

volumes:
  wallabag-images:
  wallabag-data:
```
