### ISSUE TITLE
Wallabag/mariadb healthcheck fails: mysqladmin is not included in the official container 

### ISSUE THREAD

**Issue by jeff47** [wallabag/docker#381]
The healthcheck statement in the docker compose example fails, because mysqladmin is not included in the official mariadb container.  

https://mariadb.org/mariadb-server-docker-official-images-healthcheck-without-mysqladmin/

I think the new format should be
```
      healthcheck:
            test: ['CMD', '/usr/local/bin/healthcheck.sh', '--innodb_initialized']
            start_period: 5s
            timeout: 5s
            interval: 5s
            retries: 5
```
Source: https://github.com/MariaDB/mariadb-docker/issues/512#issuecomment-1608976749
