### ISSUE TITLE
Import from Pocket

### ISSUE THREAD

**Issue by andrea-mengascini** [wallabag/docker#387]
Hi, I have a problem with the pocket import. This is my docker compose yaml file with nginx.
```yml
version: '2'

services:
  wallabag:
    image: wallabag/wallabag
    expose:
        - '80'
    environment:
      SYMFONY__ENV__DOMAIN_NAME: https://MY-DOMAIN
      VIRTUAL_HOST: MY-DOMAIN
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: 'MY-DOMAIN'
    volumes:
      - /opt/wallabag/images:/var/www/wallabag/web/assets/images
    healthcheck:
      test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 1m
      timeout: 3s
    depends_on:
      - redis
  redis:
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 3s
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    network_mode: bridge
    logging:
        options:
            max-size: "10m"
            max-file: "3"
    restart: unless-stopped
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=MYEMAIL
    volumes_from:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    network_mode: bridge
    restart: unless-stopped
```
 I tried with mariaDB, PostgreSQL and with the default SQLlite db but I can't import pocket elements. As soon as I import from pocket these 2 docker start:
`ac4557efe361   wallabag/wallabag:latest   "/entrypoint.sh impo…"   7 seconds ago    Up 2 seconds    80/tcp                              wallabag_import-pocket.1.c7l0cmpixstectpuhjxi4wxde`
`11da91bcf798   wallabag/wallabag:latest   "/entrypoint.sh impo…"   37 seconds ago   Up 32 seconds   80/tcp                              wallabag_import-instapaper.1.1q03v4nx5e66jd9hb2dptf6zi`
But their output look look like this:
```
Waiting for database ...
Waiting for database ...
Waiting for database ...
psql: error: connection to server at "db" (172.16.21.2), port 5432 failed: FATAL:  the database system is starting up
```
Even if I didn't specify postgresSQL as a database.
