### ISSUE TITLE
Refuses non-localhost connections 

### ISSUE THREAD

**Issue by EorlBrother** [wallabag/docker#41]
I recently changed the setup for my self hosted stuff from shellscripts to a docker-compose setup.
Since I restarted everything today wallabag works at first (for some minutes) but then refuses every connection which doesn't come from localhost. 
This ultimately results in a 502 on jwilder/nginx-proxy (but nothing arrives at wallabags nginx). By using telnet I can connect to the nginx on the wallabag but not from any other container on the same network. The wallabag container is still pingable. 

The relvant parts of my docker compose: 

```
 services:
  nginx_proxy:
    image: jwilder/nginx-proxy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - web
      - nginx
  nginx_companion:
    depends_on:
      - nginx_proxy
    image: alastaircoote/docker-letsencrypt-nginx-proxy-companion:latest
    restart: always
    volumes:
      - certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx_proxy
    networks:
      - nginx
  wallabag_mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - wallabag_db_data:/var/lib/mysql
    networks:
      - wallabag
    environment:
      MYSQL_ROOT_PASSWORD: some_pw
      MYSQL_DATABASE: wallabag
      MYSQL_USER: wallabag
      MYSQL_PASSWORD: some_pw
  wallabag_redis:
    image: redis:alpine
    networks:
     - wallabag
  wallabag:
    depends_on:
      - nginx_companion
      - wallabag_mariadb
      - wallabag_redis
    image: wallabag/wallabag
    restart: always
    volumes:
      - wallabag_data:/var/www/wallabag/data
      - wallabag_config:/var/www/wallabag/app/config
    networks:
      - wallabag
      - web
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: wallabag.some_domain
      LETSENCRYPT_HOST: wallabag.some_domain
      LETSENCRYPT_EMAIL: admin@some_domain
      MYSQL_ROOT_PASSWORD: some_pw
      SYMFONY__ENV__DATABASE_DRIVER: pdo_sqlite
      SYMFONY__ENV__FOSUSER_REGISTRATION: "false"

volumes:
  certs:
  vhost:
  html:

networks:
  web:
    driver: bridge
  nginx:
    driver: bridge
 
```

When I rebuild the containers wallabag works for some minutes and then randomly gets into this state, but sometimes it also reappears. I doubt that the nginx_proxy is at fault here, because my other services still work. 
Might this be some kind of performance issue? The strange part about that would be the nginx already refusing connections, without having done anything else.
