### ISSUE TITLE
500 server error with nginx-proxy and docker-compose

### ISSUE THREAD

**Issue by razaborg** [wallabag/docker#57]
Hi,

I'm trying to use wallabag with the  [jwilder/nginx-proxy](https://hub.docker.com/r/jwilder/nginx-proxy/). I can't figure out why the server is always responding with a 500 error.

The proxy seems to works well given that I got the connection logs using the `docker-compose logs`.

````
wallabag       | 2017/03/08 14:19:24 [error] 309#309: *3 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Exception: Could not gather sufficient random data in /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php:46
wallabag       | Stack trace:
wallabag       | #0 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/TokenGenerator/UriSafeTokenGenerator.php(46): random_bytes(32)
wallabag       | #1 /var/www/wallabag/vendor/symfony/symfony/src/Symfony/Component/Security/Csrf/CsrfTokenManager.php(57): Symfony\Component\Security\Csrf\TokenGenerator\UriSafeTokenGenerator->generateToken()
wallabag       | #2 /var/www/wallabag/vendor/friendsofsymfony/user-bundle/Controller/SecurityController.php(53): Symfony\Component\Security\Csrf\CsrfTokenManager->getToken('authenticate')
wallabag       | #3 [internal function]: FOS\UserBundle\Controller\SecurityController->loginAction(Object(Symfony\Component\HttpFoundation\Request))
wallabag       | #4 /var/www/wallabag/var/cache/prod/classes.php(4651): call_user_func_array(Array, Array)
wallabag       | #5 /var/www/wallabag/var/cache/prod/classes.php(4606): Symfony\C" while reading response header from upstream, client: ::ffff:172.19.0.7, server: _, request: "GET /login HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "wallabag.mysite.tld"
````
Here is my docker-compose : 

````
 
version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    ports:
      - "443:443"
    volumes:
      - /srv/seedbox/htpasswd:/etc/nginx/htpasswd
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /srv/certs:/etc/nginx/certs

  wallabag:
    image: wallabag/wallabag:latest
    container_name: "wallabag"
    links:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=myrootpass
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=mariadb
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__SECRET=mysecret
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=mypass
      - SYMFONY__ENV__MAILER_HOST=127.0.0.1
      - SYMFONY__ENV__MAILER_USER=~
      - SYMFONY__ENV__MAILER_PASSWORD=~
      - SYMFONY__ENV__FROM_EMAIL=wallabag@mysite.tld
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wallabag.mysite.tld
      - VIRTUAL_PROTO=https


  mariadb:
    image: linuxserver/mariadb:latest
    container_name: "mariadb"
    ports:
      - 3306:3306
    volumes:
      - /srv/mariadb:/config
````

Any clues about where the problem could come from ?
