### ISSUE TITLE
Database creation when using Docker and Postgres

### ISSUE THREAD

**Issue by francis-io** [wallabag/docker#81]
I have a postgres container with a database called wallabag, username wallabag and password wallabag.

I want to run the latest wallabag container via docker compose, which currently looks like this:

```
wallabag:
    container_name: wallabag
    image: wallabag/wallabag
    ports:
      - "4444:80"
    environment:
        POSTGRES_PASSWORD: wallabag
        POSTGRES_USER: wallabag
        POPULATE_DATABASE: 'False'
        SYMFONY__ENV__DATABASE_DRIVER: pdo_pgsql
        SYMFONY__ENV__DATABASE_HOST: postgres
        SYMFONY__ENV__DATABASE_PORT: 5432
        SYMFONY__ENV__DATABASE_NAME: wallabag
        SYMFONY__ENV__DATABASE_USER: wallabag
        SYMFONY__ENV__DATABASE_PASSWORD: wallabag
    volumes:
      - /tmp/wallabag-images:/var/www/wallabag/web/assets/images
```

This seems to not create the databases needed. I see [HERE](https://github.com/wallabag/docker#upgrading) it mentions migrations, but when I run them it fails with "Error There is no table with name 'wallabag.wallabag_entry' in the schema.". 

```
$ sudo docker exec -t c91 /var/www/wallabag/bin/console doctrine:migrations:migrate --env=prod --no-interaction
                                                              
                    Application Migrations                    
                                                              

Migrating up to 20170127093841 from 0

  ++ migrating 20160410190541

Migration 20160410190541 failed during Execution. Error There is no table with name 'wallabag.wallabag_entry' in the schema.

                                                                        
  [Doctrine\DBAL\Schema\SchemaException]                                
  There is no table with name 'wallabag.wallabag_entry' in the schema.  
                                                                        

doctrine:migrations:migrate [--write-sql] [--dry-run] [--query-time] [--allow-no-migration] [--configuration [CONFIGURATION]] [--db-configuration [DB-CONFIGURATION]] [--db DB] [--em EM] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command> [<version>]
```

I see this exact issue seems to have come up before [HERE](https://github.com/wallabag/docker/issues/49) but as above it looks like I need more than just the migration.

Am I missing an initial creation step?
