### ISSUE TITLE
Provisioner ignores SYMFONY__ENV__DATABASE_CHARSET

### ISSUE THREAD

**Issue by pfa230** [wallabag/docker#94]
Wallabag is configured like this in docker-compose.yml:

```
wallabag:
    image: wallabag/wallabag:2.3.0
    environment:
      MYSQL_ROOT_PASSWORD: <skipped>
      SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
      SYMFONY__ENV__DATABASE_HOST: mariadb
      SYMFONY__ENV__DATABASE_PORT: 3306
      SYMFONY__ENV__DATABASE_NAME: wallabag
      SYMFONY__ENV__DATABASE_USER: wallabag
      SYMFONY__ENV__DATABASE_PASSWORD: <skipped>
      SYMFONY__ENV__DATABASE_CHARSET: utf8mb4
      SYMFONY__ENV__MAILER_HOST: smtp
      SYMFONY__ENV__MAILER_USER: ""
      SYMFONY__ENV__MAILER_PASSWORD: ""
      SYMFONY__ENV__FROM_EMAIL: <skipped>
      SYMFONY__ENV__FOSUSER_REGISTRATION: "true"
      SYMFONY__ENV__DOMAIN_NAME: <skipped>
      SYMFONY__ENV__SECRET: <skipped>
    restart: unless-stopped
    links:
      - redis:redis
    expose:
      - 80
    depends_on:
      - smtp
      - redis
      - mariadb
      - nginx
```

No matter what I do, parameters.yml have utf8 as an charset instead of utf8mb4:

```
# docker exec -it dockerconfig_wallabag_1 grep database_charset /var/www/wallabag/app/config/parameters.yml
    database_charset: utf8

```
